import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@fontsource/inter";
import AppProvider from "@/components/AppProvider";
import Template from "@/components/Template";
import "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <Template>{children}</Template>
        </AppProvider>
      </body>
    </html>
  );
}
